steps:
  # Étape 1 : Construire l'image Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/helpdesk-streamlit', '.']
  
  # Étape 2 : Push de l'image Docker vers Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/helpdesk-streamlit']

  # Étape 3 : Déploiement sur Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'your-streamlit-app'
      - '--image=gcr.io/$PROJECT_ID/helpdesk-streamlit'
      - '--platform=managed'
      - '--region=europe-west9'
      - '--allow-unauthenticated'
      - '--update-env-vars=GCP_PROJECT=$PROJECT_ID'

# Paramètres généraux du Cloud Build
timeout: '1600s'
